/**
 * Confirms the packaged artefact actually contains what the app needs at run
 * time. The probe checks the app boots and serves its assets; this checks the
 * bundle itself, so a missing directory is caught at package time rather than
 * the first time someone runs OCR.
 *
 * usage: node scripts/verify-package.cjs [unpackedDir]
 */
const asar = require('@electron/asar');
const fs = require('node:fs');
const path = require('node:path');

const root = process.argv[2] || 'release/win-unpacked';
const asarPath = path.join(root, 'resources', 'app.asar');

let failed = 0;
const check = (label, ok, detail) => {
  console.log(`${ok ? 'OK  ' : 'FAIL'}  ${label}${detail ? `  ${detail}` : ''}`);
  if (!ok) failed++;
};

const files = asar.listPackage(asarPath).map((f) => f.split(path.sep).join('/'));
const under = (dir) => files.filter((f) => f.startsWith(`/dist/${dir}/`)).length;

// The renderer and the main process.
check('index.html', files.includes('/dist/index.html'));
check('main.cjs', files.includes('/dist-electron/main.cjs'));
check('preload.cjs', files.includes('/dist-electron/preload.cjs'));
check('renderer bundle', under('assets') > 0, `${under('assets')} files`);

// Fetched by URL at run time, so a missing directory fails only on the feature
// that needs it -- OCR most expensively, after the user has waited.
check('pdf.js cmaps', under('cmaps') > 100, `${under('cmaps')} files`);
check('standard fonts', under('standard_fonts') > 10, `${under('standard_fonts')} files`);
check('tesseract worker + cores', under('tesseract') >= 9, `${under('tesseract')} files`);
check('OCR language data', under('tessdata') === 2, `${under('tessdata')} files`);
check('Hebrew font', under('fonts') === 1, `${under('fonts')} file`);
// Without this the reader's text layer renders a pile of unpositioned spans:
// pdf.js sets per-span custom properties that only these rules consume. It is
// generated by copy-assets.mjs, so a staging change could drop it silently and
// only the packaged build would show it.
check('pdf.js text-layer CSS', files.includes('/dist/pdfjs-textlayer.css'));

// qpdf ships outside the asar: it must be a real executable on disk to spawn.
const qpdfDir = path.join(root, 'resources', 'qpdf');
const qpdf = fs.existsSync(path.join(qpdfDir, 'qpdf.exe'));
const dlls = fs.existsSync(qpdfDir)
  ? fs.readdirSync(qpdfDir).filter((f) => f.endsWith('.dll')).length
  : 0;
check('qpdf.exe sidecar', qpdf);
// Shipped from the msvc64 zip so the app does not depend on the VC++
// redistributable being installed on the target machine.
check('qpdf runtime DLLs', dlls >= 8, `${dlls} DLLs`);
check('qpdf licence', fs.existsSync(path.join(qpdfDir, 'LICENSE.txt')));

console.log(failed === 0 ? '\nPACKAGE CONTENTS OK' : `\nPACKAGE INCOMPLETE: ${failed} problem(s)`);
process.exit(failed === 0 ? 0 : 1);
